version: '3.9'
services:
  api:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    env_file:
      - ../backend/.env.example
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
